on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Render slides in PDF

jobs:
  render-readme:
    runs-on: macOS-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2

      - name: Render README
        run: Rscript -e 'install.packages("renderthis"); renderthis::to_pdf("principles.html"); renderthis::to_pdf("rselenium.html")'

      - name: Commit Results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -m 'Rendered slides in PDF' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
